HEADERS += \
    $$PWD/src/option.h

INCLUDEPATH += $$PWD/

DISTFILES += \
        $$PWD/option

CONFIG += QOPTION_INCLUDED
CONFIG += OPTION_INCLUDED
DEFINES += QOPTION_INCLUDED
DEFINES += OPTION_INCLUDEDS
